################################
#Server set
################################
server:
      port: 8082
sys.environment: PRD

################################
#Debug set
################################
spring.devtools.restart.enabled: true
spring.devtools.restart.additional-paths: src/main/java
restart.include.mapper: /mapper-[\\w-\\.]+jar
restart.include.pagehelper: /pagehelper-[\\w-\\.]+jar    
################################
#Spring 
################################
#http encoding  
spring.http.encoding.charset: UTF-8  
spring.http.encoding.enabled: true  
spring.http.encoding.force: true 
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource  
spring.datasource.url: jdbc:mysql://192.168.1.201:3366/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=PRC&useSSL=false
spring.datasource.username: admin
spring.datasource.password: admin1234
spring.datasource.driverClassName: com.mysql.jdbc.Driver

################################
#Mvc  set   
################################
spring.mvc.static-path-pattern: /static/**
#spring:
# mvc:
#  view:
#   prefix: /WEB-INF/views/
#   suffix: .jsp

#generator 自动生成代码
generator.javaModelGenerator: com.webpu.m.entity
generator.sqlMapGenerator: mappings
generator.javaClientGenerator: com.webpu.m.mapper
generator.MapperPlugin: com.webpu.m.common.generator.MyMapper
#dataSource Pool configuration
#初始化大小
spring.datasource.initialSize: 5
#空闲连接池的大小
spring.datasource.minIdle: 5
#最大激活数量
spring.datasource.maxActive: 20
#
spring.datasource.maxWait: 60000  
#?
spring.datasource.timeBetweenEvictionRunsMillis: 60000
#?
spring.datasource.minEvictableIdleTimeMillis: 300000
spring.datasource.validationQuery: SELECT 1 FROM DUAL
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
#??
spring.datasource.exceptionSorter: true
#?
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
#?
spring.datasource.filters: stat,wall,log4j
#?
spring.datasource.connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#
spring.datasource.useGlobalDataSourceStat: true
# druid  set 
spring.datasource.druid.initial-size: 1
spring.datasource.druid.min-idle: 1
spring.datasource.druid.max-active: 20
spring.datasource.druid.test-on-borrow: true
spring.datasource.druid.stat-view-servlet.allow: true
################################
# Mybatis  set   
################################
mybatis:
      type-aliases-package: com.webpu.m.pojo
      mapper-locations: classpath:mapping/*.xml
    
mapper:
      mappers:
        - com.webpu.m.common.MyMapper
      not-empty: false
      identity: MYSQL

pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql
################################
# Log  set   
################################
logging.file: /export/log  
logging.level.root: INFO  
logging.level.org.springframework.web: INFO  
logging.level.sample.mybatis.mapper: TRACE 
################################
# Freemarker  set   
################################
freemarker:
      template-loader-path: classpath:/templates
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl   
################################
# thymeleaf begin set
################################
thymeleaf:
      prefix: classpath:/templates/
      cache: false
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
      suffix: .html